name: tree_harmonizer_nb
channels:
  - etetoolkit
  - conda-forge
  - defaults
dependencies:
  - python==3.6.15
  - ete_toolchain=3.0.0
  - ete3==3.1.3
  - pandas==1.1.5
  - ipykernel
  - jupyter_core
  - jupyter_client
  - ca-certificates  
  - pip
  - pip:
    - intervaltree==3.1.0

