name: tree_harmonizer
channels:
  - etetoolkit
  - conda-forge
  - defaults
dependencies:
  - python==3.12
  - ete3==3.1.3
  - pandas==2.3.3
  - ca-certificates  
  - pip
  - pip:
    - intervaltree==3.1.0

